spring:
  application:
    name: spring-is-cool
  main:
    web-application-type: none
    keep-alive: true

spring-is-cool:
  ssh:
    enabled: true
    host: 127.0.0.1
    port: 2222
    demo-user: demo
    demo-password: demo
    host-key-path: build/ssh/hostkey.ser
