package com.hchjeong.springiscool.ai

import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import com.hchjeong.springiscool.cinematic.renderer.RevealMode
import com.hchjeong.springiscool.cinematic.renderer.Scene
import com.hchjeong.springiscool.cinematic.renderer.SceneLine
import com.hchjeong.springiscool.cinematic.renderer.SceneStyle
import com.hchjeong.springiscool.cinematic.scene.SceneDefinition
import com.hchjeong.springiscool.cinematic.scene.SceneDefinitionLoader
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.stereotype.Component

@Component
@ConditionalOnProperty(prefix = "spring-is-cool.ai", name = ["provider"], havingValue = "gemini")
class GeminiAiDirector(
    private val properties: AiDirectorProperties,
    private val client: GeminiTextClient,
    private val callLimiter: AiProviderCallLimiter,
    private val sceneDefinitionLoader: SceneDefinitionLoader,
) : AiDirector {
    private val objectMapper = jacksonObjectMapper()
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

    override fun direct(request: AiDirectorRequest): AiDirectorResult {
        if (!properties.enabled) {
            return fallback("${properties.provider} provider is configured but disabled.")
        }

        val limit = callLimiter.tryAcquire(
            provider = properties.provider,
            modelId = properties.modelId,
        )
        if (!limit.allowed) {
            return fallback(
                "${limit.provider} provider monthly call limit reached for ${limit.month}: " +
                    "${limit.used}/${limit.limit}.",
            )
        }

        return runCatching {
            val text = client.generate(promptFor(request))
            val definition = parseSceneDefinition(extractJson(text))
            AiDirectorResult.Generated(
                scene = sceneDefinitionLoader.toScene(definition),
                definition = definition,
                reviewNotes = listOf(
                    "Generated by Gemini provider `${properties.modelId}`.",
                    "Validated as SceneDefinition before rendering.",
                ),
            )
        }.getOrElse {
            fallback("${properties.provider} provider failed: ${it.message.orEmpty().ifBlank { it::class.simpleName.orEmpty() }}")
        }
    }

    private fun parseSceneDefinition(json: String): SceneDefinition {
        val root = objectMapper.readTree(json)
        require(root.isObject) { "Provider output must be one SceneDefinition JSON object." }
        requireStringField(root, "id")
        require(root.path("lines").isArray) { "Field `lines` must be an array." }
        root.path("lines").forEachIndexed { index, line ->
            require(line.isObject) { "Provider line ${index + 1} must be a JSON object." }
            listOf("text", "art", "style", "reveal", "alignment").forEach { field ->
                requireStringField(line, field, "Line ${index + 1} field `$field`")
            }
        }
        return objectMapper.readValue(root.toString())
    }

    private fun requireStringField(node: JsonNode, field: String, label: String = "Field `$field`") {
        if (node.has(field) && !node.path(field).isTextual) {
            error("$label must be a string.")
        }
    }

    private fun promptFor(request: AiDirectorRequest): String {
        return """
            You write one short AI clerk response for Ontoloffice.

            You are the AI clerk's constrained response worker.
            You do not change world state.
            You do not invent events, evidence, users, agents, credentials, files, network state, or permissions.
            You only describe or frame the world state given in this prompt.
            If the user asks for something outside the provided world state, express uncertainty; do not invent facts.

            Return JSON only.
            The JSON must be one SceneDefinition object.
            Do not use markdown.
            Do not use ANSI escape sequences or terminal control characters.
            Do not explain your choices.

            Required top-level shape:
            {
              "id": "gemini-scene",
              "terminalWidth": 80,
              "lines": []
            }

            Each line must be:
            {
              "text": "string",
              "style": "NARRATION",
              "reveal": "INSTANT",
              "delayAfterMillis": 120
            }

            A line may use "art" instead of "text", but never both.
            The fields id, text, art, style, reveal, and alignment must be strings.
            Never return nested objects for text, art, style, reveal, or alignment.

            Allowed styles: NARRATION, SIGNAL, PROMPT, SYSTEM, DIALOGUE, WARNING, MUTED.
            Allowed reveal values: INSTANT, TYPEWRITER.
            Allowed alignments: LEFT, CENTER, RIGHT.
            Allowed art ids: ${request.availableTextArt.joinToString(", ")}.

            Tone:
            Operational, precise, quiet.
            No quests.
            No puzzles.
            No supernatural claims.
            No fake hidden events.
            No invented mystery.
            No gamified rewards, XP, levels, inventory, or achievements.

            Keep terminalWidth 80 and total lines under 8.
            Keep every text value under 64 visible characters.
            Prefer short sentences over separators, banners, tables, or long repeated punctuation.
            Do not add any fields beyond id, clearBefore, hideCursorDuringPlayback,
            showPromptAfter, terminalWidth, lines, text, art, style, reveal, alignment,
            delayAfterMillis, and characterDelayMillis.

            Before returning, silently verify:
            - Output is valid JSON.
            - Output starts with { and ends with }.
            - lines is an array.
            - Every line has exactly one of text or art.
            - text/art/style/reveal/alignment are strings when present.
            - No field contains ANSI escape characters.
            - No line invents world facts not present in this prompt.
            If any check fails, rewrite the JSON before returning.

            User text: ${request.userText}
            World:
            - actor: ${request.worldSummary.actorId}
            - telephoneRinging: ${request.worldSummary.telephoneRinging}
            - lineAnswered: ${request.worldSummary.lineAnswered}
            - lineOffline: ${request.worldSummary.lineOffline}
            - eventCount: ${request.worldSummary.eventCount}
            Facts:
            ${request.worldSummary.facts.joinToString("\n")}
            Recent events:
            ${request.worldSummary.recentEvents.joinToString("\n")}
        """.trimIndent()
    }

    private fun extractJson(text: String): String {
        val trimmed = text.trim()
        val fenced = Regex("```(?:json)?\\s*(\\{.*})\\s*```", RegexOption.DOT_MATCHES_ALL)
            .find(trimmed)
            ?.groupValues
            ?.get(1)

        return fenced ?: trimmed.substring(trimmed.indexOf('{'), trimmed.lastIndexOf('}') + 1)
    }

    private fun fallback(reason: String): AiDirectorResult.Fallback {
        return AiDirectorResult.Fallback(
            scene = Scene(
                lines = listOf(
                    SceneLine(
                        text = "AI provider signal collapsed. Static control retained.",
                        reveal = RevealMode.TYPEWRITER,
                        style = SceneStyle.WARNING,
                        delayAfterMillis = 260,
                    ),
                    SceneLine(
                        text = "The failure was recorded in the local event log.",
                        reveal = RevealMode.INSTANT,
                        style = SceneStyle.MUTED,
                        delayAfterMillis = 180,
                    ),
                ),
            ),
            reason = reason,
        )
    }
}
