package com.hchjeong.springiscool.ai

import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import com.hchjeong.springiscool.cinematic.renderer.RevealMode
import com.hchjeong.springiscool.cinematic.renderer.Scene
import com.hchjeong.springiscool.cinematic.renderer.SceneLine
import com.hchjeong.springiscool.cinematic.renderer.SceneStyle
import com.hchjeong.springiscool.cinematic.scene.SceneDefinition
import com.hchjeong.springiscool.cinematic.scene.SceneDefinitionLoader
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.stereotype.Component

@Component
@ConditionalOnProperty(prefix = "spring-is-cool.ai", name = ["provider"], havingValue = "gemini")
class GeminiAiDirector(
    private val properties: AiDirectorProperties,
    private val client: GeminiTextClient,
    private val sceneDefinitionLoader: SceneDefinitionLoader,
) : AiDirector {
    private val objectMapper = jacksonObjectMapper()
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

    override fun direct(request: AiDirectorRequest): AiDirectorResult {
        if (!properties.enabled) {
            return fallback("Gemini provider is configured but disabled.")
        }

        return runCatching {
            val text = client.generate(promptFor(request))
            val definition = objectMapper.readValue<SceneDefinition>(extractJson(text))
            AiDirectorResult.Generated(
                scene = sceneDefinitionLoader.toScene(definition),
                definition = definition,
                reviewNotes = listOf(
                    "Generated by Gemini provider `${properties.modelId}`.",
                    "Validated as SceneDefinition before rendering.",
                ),
            )
        }.getOrElse {
            fallback("Gemini provider failed: ${it.message.orEmpty().ifBlank { it::class.simpleName.orEmpty() }}")
        }
    }

    private fun promptFor(request: AiDirectorRequest): String {
        return """
            Create one compact Ontoloffice SceneDefinition JSON object.
            Return JSON only. Do not use markdown. Do not emit ANSI.
            Use only these text art asset ids: ${request.availableTextArt.joinToString(", ")}.
            Keep terminalWidth 80 and total lines under 8.
            Keep every text value under 64 visible characters.
            Prefer short sentences over separators, banners, tables, or long repeated punctuation.
            The object must match this shape:
            {
              "id": "gemini-scene",
              "terminalWidth": 80,
              "lines": [
                {
                  "text": "short terminal-safe text",
                  "style": "SYSTEM",
                  "reveal": "INSTANT",
                  "delayAfterMillis": 120
                }
              ]
            }
            Allowed styles: NARRATION, SIGNAL, PROMPT, SYSTEM, DIALOGUE, WARNING, MUTED.
            Allowed reveal values: INSTANT, TYPEWRITER.
            Each line must contain either text or art, never raw terminal control sequences.
            Do not add any fields beyond id, clearBefore, hideCursorDuringPlayback,
            showPromptAfter, terminalWidth, lines, text, art, style, reveal, alignment,
            delayAfterMillis, and characterDelayMillis.

            User text: ${request.userText}
            World:
            - actor: ${request.worldSummary.actorId}
            - telephoneRinging: ${request.worldSummary.telephoneRinging}
            - lineAnswered: ${request.worldSummary.lineAnswered}
            - lineOffline: ${request.worldSummary.lineOffline}
            - eventCount: ${request.worldSummary.eventCount}
            Facts:
            ${request.worldSummary.facts.joinToString("\n")}
            Recent events:
            ${request.worldSummary.recentEvents.joinToString("\n")}
        """.trimIndent()
    }

    private fun extractJson(text: String): String {
        val trimmed = text.trim()
        val fenced = Regex("```(?:json)?\\s*(\\{.*})\\s*```", RegexOption.DOT_MATCHES_ALL)
            .find(trimmed)
            ?.groupValues
            ?.get(1)

        return fenced ?: trimmed.substring(trimmed.indexOf('{'), trimmed.lastIndexOf('}') + 1)
    }

    private fun fallback(reason: String): AiDirectorResult.Fallback {
        return AiDirectorResult.Fallback(
            scene = Scene(
                lines = listOf(
                    SceneLine(
                        text = "Gemini signal collapsed. Static control retained.",
                        reveal = RevealMode.TYPEWRITER,
                        style = SceneStyle.WARNING,
                        delayAfterMillis = 260,
                    ),
                    SceneLine(
                        text = reason.take(140),
                        reveal = RevealMode.INSTANT,
                        style = SceneStyle.MUTED,
                        delayAfterMillis = 180,
                    ),
                ),
            ),
            reason = reason,
        )
    }
}
